import keyMirror from 'key-mirror'

export default keyMirror({
  SET_PLATFORM: null,
  SET_VERSION: null,
  SET_THEME: null,

  SESSION_TOKEN_REQUEST: null,
  SESSION_TOKEN_SUCCESS: null,
  SESSION_TOKEN_FAILURE: null,

  DELETE_TOKEN_REQUEST: null,
  DELETE_TOKEN_SUCCESS: null,

  ON_LOGIN_STATE_CHANGE: null,
  LOGOUT: null,

  ON_AUTH_FORM_FIELD_CHANGE: null,
  SIGNUP_REQUEST: null,
  SIGNUP_SUCCESS: null,
  SIGNUP_FAILURE: null,

  LOGIN_REQUEST: null,
  LOGIN_SUCCESS: null,
  LOGIN_FAILURE: null,

  LOGOUT_REQUEST: null,
  LOGOUT_SUCCESS: null,
  LOGOUT_FAILURE: null,

  LOGGED_IN: null,
  LOGGED_OUT: null,

  SET_SESSION_TOKEN: null,

  RESET_PASSWORD_REQUEST: null,
  RESET_PASSWORD_SUCCESS: null,
  RESET_PASSWORD_FAILURE: null,

  GET_PROFILE_REQUEST: null,
  GET_PROFILE_SUCCESS: null,
  GET_PROFILE_FAILURE: null,

  ON_PROFILE_FORM_FIELD_CHANGE: null,

  PROFILE_UPDATE_REQUEST: null,
  PROFILE_UPDATE_SUCCESS: null,
  PROFILE_UPDATE_FAILURE: null,

  SET_STATE: null,
  GET_STATE: null,
  SET_STORE: null,

  FORGOT_PASSWORD: null,
  LOGIN: null,
  REGISTER: null,

  EDITPROFILE: null,
  MYPROFILE: null,
  NOPROFILE: null,

  TASKLIST: null,
  TASKEDIT: null,

  TASKLIST_REQUEST: null,
  TASKLIST_SUCCESS: null,
  TASKLIST_FAILURE: null,

  ADDTASK_REQUEST: null,
  ADDTASK_SUCCESS: null,
  ADDTASK_FAILURE: null,

  ENVDLIST: null,
  STEP1: null,
  STEP2: null,
  STEP3: null,
  STEP4: null,
  STEP5: null,
  STEP6: null,
  STEP7: null,
  STEP8: null,

  ADD_STEP1_DATA: null,
  ADD_STEP2_DATA: null,
  ADD_STEP3_DATA: null,
  ADD_STEP4_DATA: null,
  ADD_STEP5_DATA: null,
  ADD_STEP6_DATA: null,
  ADD_STEP7_DATA: null,

  ENVDLIST_REQUEST: null,
  ENVDLIST_SUCCESS: null,
  ENVDLIST_FAILURE: null,

  GETENVD_REQUEST: null,
  GETENVD_SUCCESS: null,
  GETENVD_FAILURE: null,

  ADDENVD_REQUEST: null,
  ADDENVD_SUCCESS: null,
  ADDENVD_FAILURE: null,

  ACTIVITY_LIST_REQUEST: null,
  ACTIVITY_LIST_SUCCESS: null,
  ACTIVITY_LIST_FAILURE: null

})
